enum Status {
    LOADING='LOADING',
    LOADED_NORMAL='LOADED_NORMAL',
    LOADED_EMPTY='LOADED_EMPTY',
    LOADED_NO_MORE='LOADED_NO_MORE',
    LOADED_EMPTY_WITH_DATAFILTER='LOADED_EMPTY_WITH_DATAFILTER',
    ERROR='ERROR',
}

export default Status